### ISSUE TITLE
How to connect GoDaddy domain and React frontend and Express backend servers deployed on EC2 instance?

### ISSUE THREAD

**Issue by vincent157664** [vincent157664/auxilar_backend#1]
How are you?

I've deployed React frontend and Express backend on EC2 instance and the project is running well. To migrate server from HTTP to HTTPS, I've installed NGINX and CertBot on EC2 instance. The frontend is successfully deployed, but the backend is not configured. Please help me. Thanks.

**Comment by waytothesmarse** [comment]
You can configure the NGINX configure file to serve for frontend and backend at the same time.

**Comment by vincent157664** [comment]
Please share NGINX configure file please.

**Comment by waytothevenus** [comment]
# Redirect HTTP traffic to HTTPS for main domain
server {
    listen 80;
    server_name your_domain www.yourdomain;

    location / {
        return 301 https://$host$request_uri;
    }
}

# Redirect HTTP traffic to HTTPS for backend subdomain
server {
    listen 80;
    server_name subdomain;

    location / {
        return 301 https://$host$request_uri;
    }
}

# Frontend server block - main domain
server {
    listen 443 ssl;
    server_name auxilar.org www.auxilar.org;

    # SSL configuration
    ssl_certificate /etc/letsencrypt/live/auxilar.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/auxilar.org/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # Root directory for the frontend build files
    root /root/Auxilar-frontend/build;
    index index.html;

    location / {
        try_files $uri /index.html =404;
    }
}

# Backend server block - subdomain
server {
    listen 443 ssl;
    server_name backend.auxilar.org;

    # SSL configuration
    ssl_certificate /etc/letsencrypt/live/backend.auxilar.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/backend.auxilar.org/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
      ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location /api/ {
        proxy_pass http://localhost:3030;
        client_max_body_size 100M;
        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

**Comment by waytothevenus** [comment]
This is my working config file for frontend and backend.

**Comment by vincent157664** [comment]
Thanks. I will try.

**Comment by vincent157664** [comment]
That works. Thanks.
